# Generated by Django 4.0 on 2022-11-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('start_long', models.DecimalField(decimal_places=6, max_digits=8)),
                ('start_lat', models.DecimalField(decimal_places=6, max_digits=8)),
                ('end_long', models.DecimalField(decimal_places=6, max_digits=8)),
                ('end_lat', models.DecimalField(decimal_places=6, max_digits=8)),
            ],
        ),
    ]
