# Generated by Django 4.1.3 on 2023-01-03 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0002_location"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Location",
            new_name="Map",
        ),
    ]
