# Generated by Django 4.1.5 on 2023-01-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_rename_location_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='address',
        ),
        migrations.RemoveField(
            model_name='map',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='map',
            name='longitude',
        ),
        migrations.AddField(
            model_name='map',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='map',
            name='lon',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
