# Generated by Django 4.1.5 on 2023-01-15 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=8)),
                ('long', models.DecimalField(decimal_places=6, max_digits=8)),
                ('type', models.CharField(max_length=128)),
                ('dispatched_to', models.BooleanField(default=False)),
                ('resolved', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2023, 1, 15, 16, 35, 58, 42557, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_name', models.CharField(max_length=128, unique=True)),
                ('last_ping', models.DateTimeField(default=datetime.datetime(2023, 1, 15, 16, 35, 58, 41562, tzinfo=datetime.timezone.utc))),
                ('lat', models.DecimalField(decimal_places=6, max_digits=8)),
                ('long', models.DecimalField(decimal_places=6, max_digits=8)),
                ('currently_dispatch', models.BooleanField(default=False)),
            ],
        ),
    ]
