# Generated by Django 4.1.5 on 2023-01-24 21:28

from django.db import migrations, models
import django.db.models.deletion
import routing.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=15, max_digits=17)),
                ('long', models.DecimalField(decimal_places=15, max_digits=17)),
                ('type', models.CharField(max_length=128)),
                ('resolved', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_name', models.CharField(max_length=128)),
                ('last_ping', models.DateTimeField(auto_now_add=True)),
                ('lat', models.DecimalField(decimal_places=15, max_digits=17)),
                ('long', models.DecimalField(decimal_places=15, max_digits=17)),
                ('currently_dispatch', models.BooleanField(default=False)),
                ('currently_checked_in', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RouteRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodes', routing.fields.IntegerListField(max_length=2000, null=True)),
                ('start_linestring', models.CharField(max_length=1000, null=True)),
                ('end_linestring', models.CharField(max_length=1000, null=True)),
                ('weight', models.FloatField(null=True)),
                ('length', models.FloatField(null=True)),
                ('route_geo_json', models.CharField(max_length=9000, null=True)),
                ('emergency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routing.emergency', unique=True)),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='routing.emergencyvehicle')),
            ],
        ),
        migrations.AddField(
            model_name='emergency',
            name='dispatched_vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='routing.emergencyvehicle'),
        ),
    ]
