# Generated by Django 4.1.5 on 2023-01-15 16:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 15, 16, 39, 57, 188791, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='emergencyvehicle',
            name='last_ping',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 15, 16, 39, 57, 188791, tzinfo=datetime.timezone.utc)),
        ),
    ]
