# Generated by Django 4.1.5 on 2023-01-18 11:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0003_alter_emergency_lat_alter_emergency_long_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergency',
            name='dispatched_to',
        ),
        migrations.AddField(
            model_name='emergency',
            name='dispatched_vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='routing.emergencyvehicle'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 18, 11, 15, 15, 128032, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='emergencyvehicle',
            name='last_ping',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 18, 11, 15, 15, 127752, tzinfo=datetime.timezone.utc)),
        ),
    ]
