# Generated by Django 4.1.5 on 2023-01-23 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0004_remove_emergency_dispatched_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routerecommendation',
            name='route_geo_json',
            field=models.CharField(default={}, max_length=9000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emergency',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 23, 11, 33, 38, 37154, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='emergencyvehicle',
            name='last_ping',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 23, 11, 33, 38, 37154, tzinfo=datetime.timezone.utc)),
        ),
    ]
